- name: Clone LibreNMS Agent repository
  git:
    repo: '{{ librenms_agent_repository }}'
    dest: /opt/librenms-agent
    version: '{{ librenms_agent_version }}'

- name: Copy check_mk_agent
  copy:
    src: /opt/librenms-agent/check_mk_agent
    dest: /usr/bin/check_mk_agent
    mode: 0755
    remote_src: true

- name: Install systemd service
  copy:
    src: /opt/librenms-agent/check_mk@.service
    dest: /etc/systemd/system/check_mk@.service
    remote_src: true
  when: ansible_service_mgr == 'systemd'

- name: Install systemd service socket
  copy:
    src: /opt/librenms-agent/check_mk.socket
    dest: /etc/systemd/system/check_mk.socket
    remote_src: true
  when: ansible_service_mgr == 'systemd'

- name: Create agent directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /usr/lib/check_mk_agent/plugins
    - /usr/lib/check_mk_agent/local

- name: Install check_mk agent scripts
  copy:
    src: '/opt/librenms-agent/agent-local/{{ item }}'
    dest: '/usr/lib/check_mk_agent/local/{{ item }}'
    mode: 0755
    remote_src: true
  with_flattened: '{{ librenms_agent_check_mk_scripts }}'

- name: Enable check_mk service socket
  systemd:
    name: check_mk.socket
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd'

- name: Fix some scripts execution bit
  file:
    path: '/opt/librenms-agent/snmp/{{ item }}'
    mode: 0755
  with_items:
    - zfs-linux
    - unbound
    - asterisk
    - bind
    - chip.sh
    - entropy.sh
    - exim-stats.sh
    - fail2ban
    - fbsdnfsclient
    - fbsdnfsserver
    - freeradius.sh
    - nvidia
    - phpfpmsp
    - pi-hole
    - postgres
    - powerdns-dnsdist
    - sdfsinfo
    - smart
    - squid

