- name: Clone LibreNMS Agent repository
  git:
    repo: '{{ librenms_agent_repository }}'
    dest: /opt/librenms-agent
    version: '{{ librenms_agent_version }}'
    force: yes

- name: "get {{ ansible_os_family }} variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: Create agent directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ prefix }}/lib/check_mk_agent/plugins"
    - "{{ prefix }}/lib/check_mk_agent/local"

- name: Install check_mk agent scripts
  copy:
    src: '/opt/librenms-agent/agent-local/{{ item }}'
    dest: "{{prefix}}/lib/check_mk_agent/local/{{ item }}"
    mode: "0755"
    remote_src: true
  with_flattened: '{{ librenms_agent_check_mk_scripts }}'

- name: systemd-like post-install
  include_tasks: systemd-install.yml
  when: ansible_service_mgr == 'systemd'

- name: freebsd post-install
  include_tasks: freebsd-install.yml
  when: ansible_os_family == 'FreeBSD'

- name: Fix some scripts execution bit
  file:
    path: '/opt/librenms-agent/snmp/{{ item }}'
    mode: "0755"
  with_items:
    - zfs-linux
    - unbound
    - asterisk
    - bind
    - chip.sh
    - entropy.sh
    - exim-stats.sh
    - fail2ban
    - fbsdnfsclient
    - fbsdnfsserver
    - freeradius.sh
    - nvidia
    - phpfpmsp
    - pi-hole
    - postgres
    - powerdns-dnsdist
    - sdfsinfo
    - smart
    - zfs-freebsd

