---
- name: Copy check_mk_agent
  copy:
    src: /opt/librenms-agent/check_mk_agent
    dest: "{{ prefix }}/bin/check_mk_agent"
    mode: "0755"
    remote_src: true

- name: Install systemd service
  copy:
    src: /opt/librenms-agent/check_mk@.service
    dest: /etc/systemd/system/check_mk@.service
    remote_src: true

- name: Install systemd service socket
  copy:
    src: /opt/librenms-agent/check_mk.socket
    dest: /etc/systemd/system/check_mk.socket
    remote_src: true

- name: Enable check_mk service socket
  systemd:
    name: check_mk.socket
    state: restarted
    enabled: yes
    daemon_reload: yes
